name: Build Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release

      - name: Create portable executable with NSIS
        run: |
          choco install nsis -y
          echo 'OutFile "MyFlutterApp-Installer.exe"' > installer.nsi
          echo 'InstallDir "$PROGRAMFILES\MyFlutterApp"' >> installer.nsi
          echo 'Section' >> installer.nsi
          echo '  SetOutPath $INSTDIR' >> installer.nsi
          echo '  File /r "build\windows\x64\runner\Release\*"' >> installer.nsi
          echo '  CreateShortcut "$DESKTOP\MyFlutterApp.lnk" "$INSTDIR\your_app_name.exe"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          makensis installer.nsi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: MyFlutterApp-Installer.exe